# DLFE-LSTM-WSI Conda环境配置文件（导出版本）
# 基于动态天气状态识别和局部特征嵌入的光伏功率自适应预测方法
# 导出时间: 2025-09-26

name: dlfe-lstm-wsi
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # Python基础环境
  - python=3.9

  # 深度学习框架
  - pytorch>=1.12.0
  - torchvision
  - cudatoolkit=11.6  # GPU支持

  # 科学计算核心库
  - numpy>=1.21.0
  - scipy>=1.7.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0

  # 数据可视化
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - plotly>=5.0.0

  # 开发工具
  - jupyter
  - jupyterlab
  - ipython

  # 实验管理与监控
  - tensorboard
  - mlflow>=1.28.0

  # 配置与工具
  - pyyaml
  - tqdm
  - click
  - python-dotenv
  
  # 数据格式支持
  - openpyxl>=3.0.0

  # pip安装的专用包
  - pip
  - pip:
    # VMD变分模态分解专用
    - PyWavelets>=1.4.1
    - vmdpy>=0.2
    
    # 统计分析与时序处理
    - statsmodels>=0.14.0
    - tslearn>=0.6.0
    
    # 数值计算加速
    - numba>=0.57.1
    
    # 超参数优化
    - optuna>=3.0.0
    - hyperopt>=0.2.7
    
    # 实验追踪（可选）
    - wandb>=0.13.0
    
    # ADMM优化算法支持
    - cvxpy>=1.3.0
    - cvxopt>=1.3.0
    
    # 气象数据处理（CI清晰度指数计算）
    - astral>=3.0
    - pyephem>=4.1
    
    # 地理信息处理
    - geopy>=2.3.0
    
    # 时序预测评估
    - sktime>=0.15.0
    
    # 并行计算
    - joblib>=1.2.0
    
    # 数据格式支持
    - h5py>=3.7.0
    - netcdf4>=1.6.0
    
    # 机器学习扩展（对比基准模型）
    - xgboost>=1.7.0
    - lightgbm>=3.3.0
